server:
  port: 8093

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ratingdb
    username: postgres
    password: Younis@123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  application:
    name: RATING-SERVICE


eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka